---
- name: Verificar versión de OpenSSH
  command: ssh -V
  register: ssh_version_output
  changed_when: false

- name: Mostrar versión de OpenSSH
  debug:
    msg: "La versión de OpenSSH en {{ inventory_hostname }} es {{ ssh_version_output.stderr_lines[0] }}"
  when: ssh_version_output.stderr is defined and ('OpenSSH_9.7' in ssh_version_output.stderr or 'OpenSSH_9.6' in ssh_version_output.stderr or 'OpenSSH_9.5' in ssh_version_output.stderr or 'OpenSSH_9.4' in ssh_version_output.stderr or 'OpenSSH_9.3' in ssh_version_output.stderr or 'OpenSSH_9.2' in ssh_version_output.stderr or 'OpenSSH_9.1' in ssh_version_output.stderr or 'OpenSSH_9.0' in ssh_version_output.stderr or 'OpenSSH_8.9' in ssh_version_output.stderr or 'OpenSSH_8.8' in ssh_version_output.stderr or 'OpenSSH_8.7' in ssh_version_output.stderr or 'OpenSSH_8.6' in ssh_version_output.stderr or 'OpenSSH_8.5' in ssh_version_output.stderr or 'OpenSSH_4.0' in ssh_version_output.stderr or 'OpenSSH_4.1' in ssh_version_output.stderr or 'OpenSSH_4.2' in ssh_version_output.stderr or 'OpenSSH_4.3' in ssh_version_output.stderr or 'OpenSSH_4.4' in ssh_version_output.stderr or 'OpenSSH_3' in ssh_version_output.stderr or 'OpenSSH_2' in ssh_version_output.stderr or 'OpenSSH_1' in ssh_version_output.stderr)
